# Alternative secure docker-compose for production use
# This version keeps credentials read-only and uses separate cache volume
version: '3.8'

services:
  testgen-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials (read-only)
      - aws_cache:/root/.aws/sso/cache  # Separate writable volume for SSO cache
    environment:
      - AWS_PROFILE=cengage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  aws_cache:  # Named volume for AWS SSO cache
